name: infrastructure-code

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Run test suite
      working-directory: ./iac
      run: ./gradlew check codeCoverageReport

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
          directory: ./iac
          token: ${{ secrets.CODECOV_TOKEN }}
