name: url-shortener

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: make dev

    - name: Run test suite
      run: make test

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
          file: ./coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
